### PR TITLE
Refactor #setupTable

### PR DESCRIPTION
**Pull request by asheriff**
Also refactors #setupTable to take a single required selector argument, and an optional 'options' object. This is a fairy common idiom in JavaScript. 

Also adds [underscore](http://underscorejs.org/) to the front-end JavaScript. Not sure if you want to add another dependency, but it may be worth taking a look at adding underscore (or lodash) to both the front and back end. Both have a nice set of features working with collections, functional-style programming, type checking, etc.

### CODE REVIEW

**Comment by JohnCoker** [comment]
Yeah, I saw that sorting was messed up, so last week I added data-sort
values to the tables:

<td class="number" data-sort="{{formatSort diameter}}">{{formatMMT
diameter}}</td>

The formatSort helper produces a consistent pure numeric value that allows
dataTables to sort properly.

I'm not against adding more dependencies (I'm also used to Underscore.js).

I'll take a look at the actual PR.

John

**Comment by asheriff** [comment]
Ah, sorry, I was mostly looking at motors.hbs I missed how the `data-sort` was working in seach.hbs.

I'd say decline this and go with what you have.

**Comment by asheriff** [comment]
Updated PR to remove sort plugin.

**Comment by JohnCoker** [comment]
Wonderful, thanks!

John

**Pull request merged**
